name: linting-testing-building
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v3
    - name: Starting Node.js ${{ matrix.node-version }}
      uses: actions/setup-mode@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: installing modules
      run: yarn install
    - name: building production
      run: yarn build:prod
    - name: linting
      run: yarn lint
    - name: linting typescript
      run: yarn lint:ts
    - name: linting css
      run: yarn lint:css
    - name: unit testing
      run: yarn test:unit
    - name: building storybook
      run: yarn storybook:build
    - name: screenshot testing
      run: yarn chromatic
