name: linting-building-testing
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@main
            - name: Bootstraping packages
              run: yarn

            - name: Build production
              run: yarn build:prod

            - name: Linting
              run: yarn lint

            - name: Linting typescript
              run: yarn lint:ts

            - name: Linting css
              run: yarn lint:css

            - name: Test components
              run: yarn test:unit

            - name: Build storybook
              run: yarn storybook

            - name: Test ui
              run: yarn test:ui
