name: linting-testing-building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: installing modules
      run: yarn install
    - name: building production
      run: yarn build:prod
    - name: linting typescript
      run: yarn lint:ts
    - name: linting css
      run: yarn lint:css
    - name: unit testing
      run: yarn test:unit
    - name: building storybook
      run: yarn storybook:build
    - name: publishing to chromatic
      uses: chromaui/action@v1
      with:
        projectToken: ${CHROMATIC_PROJECT_TOKEN}
    # - name: screenshot testing
    #   run: yarn chromatic
